trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      cd android
      ./gradlew clean
      ./gradlew assembleRelease --no-build-cache --rerun-tasks
    displayName: 'Build Android Release APK'

  - script: |
      npm install -g firebase-tools
    displayName: 'Install Firebase CLI'

  - script: |
      firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
        --app $FIREBASE_APP_ID \
        --token $FIREBASE_TOKEN \
        --groups testers
    displayName: 'Upload APK to Firebase App Distribution'
