trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
    displayName: 'Install Dependencies'

  - script: |
      cd android
      ./gradlew clean
      ./gradlew assembleRelease
    displayName: 'Build Android Release APK'

  - script: |
      echo "✅ Build complete! Check your android/app/build/outputs/apk/release"
    displayName: 'Show APK Output Location'
