<<<<<<< HEAD
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
=======
trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
    displayName: 'Install Dependencies'

  - script: |
      cd android
      ./gradlew clean
      ./gradlew assembleRelease
    displayName: 'Build Android Release APK'

  - script: |
      echo "✅ Build complete! Check your android/app/build/outputs/apk/release"
    displayName: 'Show APK Output Location'
>>>>>>> 78b6a12 (Add Azure pipeline for Android build)
