trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      export PATH="$PATH:$(npm bin -g)"
      node --version
      npm install
    displayName: 'Install Dependencies'

  - script: |
      mkdir -p android/app/src/main/assets
      mkdir -p android/app/src/main/res
    displayName: "Create assets & res folders"

  - script: |
      npx react-native bundle \
        --platform android \
        --dev false \
        --entry-file index.js \
        --bundle-output android/app/src/main/assets/index.android.bundle \
        --assets-dest android/app/src/main/res
    displayName: 'Bundle JS for Android Release'

  - script: |
      cd android
      ./gradlew clean
      ./gradlew assembleRelease --no-daemon --stacktrace --info
    displayName: 'Build Android Release APK'

  - script: |
      npm install -g firebase-tools
    displayName: 'Install Firebase CLI'

  - script: |
      firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
        --app '1:705816704674:android:a1d2d7929c2a314dc0c9fb' \
        --token '1//0gFglyxqgTvlQCgYIARAAGBASNwF-L9IrhGOo_alcS3tEQIOXJc1NcdMvIw2RmQ2V0fzukJOk9bjkG9CY8hi2tCaG_5Qnqlgk5Ao' \
        --groups testers
    displayName: 'Upload APK to Firebase App Distribution'
